[build]
  command   = "npm run build"
  functions = "netlify/functions"
  publish   = "dist"

[build.environment]
  NODE_VERSION = "20"

[dev]
  command   = "npm run dev"
  functions = "netlify/functions"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
